### PR TITLE
Fix notifications on Windows 10 (build 1709+)

### PR DESCRIPTION
**Pull request by MicrochipQ**
I opened this PR because it fixes notifications on new builds of Windows 10

### CODE REVIEW

**Comment by MicrochipQ** [comment]
When will the merge? This is important to me because my projects depend on this repository, and using my own fork is not the best practice.

**Comment by mikaelbr** [comment]
Out now

**Comment by MicrochipQ** [comment]
Thanks. I will be wait for publish to NPM

**Comment by mikaelbr** [comment]
It is now

**Pull request merged**
