### PR TITLE
Allow no sound by passing 'none' as value

### PR DESCRIPTION
**Pull request by piotr-cz**
```sh
notify --sound none
```

### CODE REVIEW

**Comment by mikaelbr** [comment]
Thanks 🍰 🎉

**Comment by piotr-cz** [comment]
We should update docs, too. Is something like this okay?
```
    * --sound (alias -s, use none to disable default sound notification)
```

**Comment by mikaelbr** [comment]
Good thinking. That looks fine. I added you as a collaborator. Feel free to fix it :)

**Comment by piotr-cz** [comment]
Thanks, added in efc83b71b9ae8fa06c2e34eb8718d38826e75291

**Pull request merged**
